$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: pipeline_f1
experiment_name: pipeline_f1
description: Pipeline for data preprocessing, model training, hyperparameter sweep, and registration

inputs:
  raw_data:                         # <<< changed from uri_folder to uri_file
    type: uri_file                  # <<< matches your data.yml type now
    path: azureml:cars_data_f1@latest
  model_name: "used_cars_price_prediction_model"   # <<< added: moved out of job as pipeline input

outputs:
  train_data:
    type: uri_folder
    path: azureml://datastores/newblobstorepipeline/paths/cars_data.csv  # ← updated datastore
  test_data:
    type: uri_folder
    path: azureml://datastores/newblobstorepipeline/paths/cars_data.csv  # ← updated datastore
  model_info_output_path:
    type: uri_folder
    path: azureml://datastores/newblobstorepipeline/paths/cars_data.csv  # ← updated datastore

settings:
  default_datastore: azureml:newblobstorepipeline
  default_compute: azureml:cpu-cluster
  force_rerun: true
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}          # <<< stays the same
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    name: sweep_job
    display_name: sweep-job
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model                             # <<< stays valid
    sampling_algorithm: random
    trial: ./train.yml
    search_space:
      n_estimators:
        type: choice
        values: [10, 15]
      max_depth:
        type: choice
        values: [3, 5]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 4
      max_concurrent_trials: 2
      timeout: 3600

  register_model:
    name: registermod_v1
    display_name: register-modelv1
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}}               # <<< changed from inputs to parent.inputs
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:cars-train-env@latest
    inputs:
      model_name: ${{parent.inputs.model_name}}         # <<< changed from type: literal + value
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}  # <<< stays correct
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
