$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: pipeline_v1 # Provide the display name for the pipeline
experiment_name: pipeline_v1  # Provide the experiment name
description: Pipeline for data preprocessing, model training, hyperparameter sweep, and registration  # Provide the description for the pipeline


inputs:
  raw_data:
    type: uri_file
    path: azureml:cars_data@latest

outputs:
  train_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/train_data_$(RunId)/  # Dynamic path for train data
  test_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/test_data_$(RunId)/  # Dynamic path for test data
  model_info_output_path:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/model_info_$(RunId)/  # Dynamic path for model info

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false
  force_rerun: true  # Force rerun to bypass caching

jobs:
  prep_data:
    name: prep_data  # Provide the job name
    display_name: prep-data  # Provide the display name for the job
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    name: sweep_job
    display_name: sweep-job  # Hint: Provide the display name for the job
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random  # Specify the sampling algorithm
    trial: ./train.yml  # Refers to a separate command component
    search_space:
      n_estimators:
        type: choice
        values: [10, 15]
      max_depth:
        type: choice  # Specify the type for max_depth
        values: [3,5]  # Provide the values for max_depth
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 4
      max_concurrent_trials: 2
      timeout: 3600


  register_model:
    name: registermod_v1  # Provide the job name
    display_name: register-modelv1  # Provide the display name for the job
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:cars-train-env@latest
    inputs:
      model_name: 
        type: literal 
        value: "used_cars_price_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}  
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}  


